import { PartnerProfile } from "./types";

/**
 * DEMO DATA — clearly fictional wellness partners for prototyping VitaOS
 * Connect. None of these represent real people. When a real backend is
 * wired up, this module is replaced by an API/database query and nothing
 * else in the Connect feature needs to change shape.
 */
export const MOCK_PARTNERS: PartnerProfile[] = [
  {
    id: "arjun",
    name: "Arjun",
    age: 24,
    activities: ["running"],
    distanceKm: [5, 7],
    paceMinPerKm: [6, 6.5],
    experienceLevel: "intermediate",
    preferredTime: "morning",
    availability: ["Mon", "Wed", "Fri", "Sat"],
    approxDistanceAway: "~2.1 km away",
    avatar: "🏃",
    isDemo: true,
  },
  {
    id: "priya",
    name: "Priya",
    age: 27,
    activities: ["running", "yoga"],
    distanceKm: [2, 4],
    paceMinPerKm: [6.5, 7],
    experienceLevel: "beginner",
    preferredTime: "morning",
    availability: ["Tue", "Thu", "Sat", "Sun"],
    approxDistanceAway: "~1.4 km away",
    avatar: "🧘",
    isDemo: true,
  },
  {
    id: "rohan",
    name: "Rohan",
    age: 29,
    activities: ["gym"],
    workoutType: "Strength",
    experienceLevel: "intermediate",
    preferredTime: "evening",
    availability: ["Mon", "Wed", "Fri"],
    approxDistanceAway: "~3.0 km away",
    avatar: "🏋️",
    isDemo: true,
  },
  {
    id: "aisha",
    name: "Aisha",
    age: 31,
    activities: ["walking", "sunlightWalk"],
    experienceLevel: "beginner",
    preferredTime: "evening",
    availability: ["Mon", "Tue", "Wed", "Thu", "Fri"],
    approxDistanceAway: "~0.8 km away",
    avatar: "🚶",
    isDemo: true,
  },
  {
    id: "kabir",
    name: "Kabir",
    age: 26,
    activities: ["cycling"],
    distanceKm: [8, 12],
    experienceLevel: "advanced",
    preferredTime: "morning",
    availability: ["Sat", "Sun"],
    approxDistanceAway: "~4.5 km away",
    avatar: "🚴",
    isDemo: true,
  },
  {
    id: "meera",
    name: "Meera",
    age: 23,
    activities: ["running", "hiking"],
    distanceKm: [3, 5],
    paceMinPerKm: [6, 7],
    experienceLevel: "beginner",
    preferredTime: "morning",
    availability: ["Mon", "Wed", "Sat", "Sun"],
    approxDistanceAway: "~2.6 km away",
    avatar: "🥾",
    isDemo: true,
  },
  {
    id: "dev",
    name: "Dev",
    age: 33,
    activities: ["gym", "sports"],
    workoutType: "Functional",
    experienceLevel: "advanced",
    preferredTime: "evening",
    availability: ["Tue", "Thu", "Sat"],
    approxDistanceAway: "~1.9 km away",
    avatar: "🏀",
    isDemo: true,
  },
];
