import { Exercise } from "./types";

/**
 * The exercise library. Every entry's `motion` maps to the single shared
 * <ExerciseAnimation /> component — never a one-off animation per exercise.
 */
export const EXERCISES: Exercise[] = [
  {
    slug: "squat",
    name: "Squat",
    category: "lowerBody",
    difficulty: "beginner",
    equipment: "None",
    motion: "squat",
    defaultSets: 3,
    defaultReps: "12",
    instructions: [
      "Stand with feet approximately shoulder-width apart.",
      "Keep your chest upright.",
      "Bend your knees and hips.",
      "Lower yourself in a controlled movement.",
      "Return to the starting position.",
    ],
    formCues: ["Controlled movement", "Stable posture", "Comfortable range of motion"],
  },
  {
    slug: "push-up",
    name: "Push-up",
    category: "upperBody",
    difficulty: "intermediate",
    equipment: "None",
    motion: "pushup",
    defaultSets: 3,
    defaultReps: "10",
    instructions: [
      "Place hands slightly wider than shoulder-width on the floor.",
      "Keep your body in a straight line.",
      "Lower your chest toward the floor.",
      "Push back up to the starting position.",
    ],
    formCues: ["Controlled descent", "Straight body line", "Comfortable range of motion"],
  },
  {
    slug: "lunge",
    name: "Lunge",
    category: "lowerBody",
    difficulty: "beginner",
    equipment: "None",
    motion: "lunge",
    defaultSets: 3,
    defaultReps: "10",
    instructions: [
      "Stand tall with feet hip-width apart.",
      "Step forward with one leg.",
      "Lower your hips until both knees are bent.",
      "Push back to the starting position.",
      "Alternate legs.",
    ],
    formCues: ["Controlled step", "Stable posture", "Comfortable depth"],
  },
  {
    slug: "plank",
    name: "Plank",
    category: "core",
    difficulty: "beginner",
    equipment: "None",
    motion: "plank",
    defaultSets: 3,
    defaultReps: "30 sec",
    instructions: [
      "Rest on your forearms and toes.",
      "Keep your body in a straight line.",
      "Engage your core.",
      "Hold the position while breathing steadily.",
    ],
    formCues: ["Neutral spine", "Steady breathing", "Comfortable hold duration"],
  },
  {
    slug: "glute-bridge",
    name: "Glute Bridge",
    category: "lowerBody",
    difficulty: "beginner",
    equipment: "None",
    motion: "bridge",
    defaultSets: 3,
    defaultReps: "15",
    instructions: [
      "Lie on your back with knees bent, feet flat.",
      "Press through your heels and lift your hips.",
      "Pause briefly at the top.",
      "Lower back down with control.",
    ],
    formCues: ["Controlled lift", "Engage glutes", "Comfortable range of motion"],
  },
  {
    slug: "jumping-jacks",
    name: "Jumping Jacks",
    category: "cardio",
    difficulty: "beginner",
    equipment: "None",
    motion: "jump",
    defaultSets: 3,
    defaultReps: "30 sec",
    instructions: [
      "Stand with feet together, arms at your sides.",
      "Jump while spreading your legs and raising your arms.",
      "Jump back to the starting position.",
      "Repeat at a steady pace.",
    ],
    formCues: ["Steady rhythm", "Soft landings", "Comfortable pace"],
  },
  {
    slug: "mountain-climbers",
    name: "Mountain Climbers",
    category: "cardio",
    difficulty: "intermediate",
    equipment: "None",
    motion: "plank",
    defaultSets: 3,
    defaultReps: "30 sec",
    instructions: [
      "Start in a plank position.",
      "Drive one knee toward your chest.",
      "Switch legs quickly.",
      "Keep your core engaged throughout.",
    ],
    formCues: ["Steady pace", "Stable hips", "Comfortable range of motion"],
  },
  {
    slug: "bicycle-crunch",
    name: "Bicycle Crunch",
    category: "core",
    difficulty: "intermediate",
    equipment: "None",
    motion: "twist",
    defaultSets: 3,
    defaultReps: "15",
    instructions: [
      "Lie on your back with hands behind your head.",
      "Bring one knee toward your chest while rotating the opposite elbow toward it.",
      "Switch sides in a pedaling motion.",
      "Keep the movement controlled.",
    ],
    formCues: ["Controlled rotation", "Steady breathing", "Comfortable pace"],
  },
  {
    slug: "cat-cow",
    name: "Cat-Cow Stretch",
    category: "mobility",
    difficulty: "beginner",
    equipment: "None",
    motion: "stretch",
    defaultSets: 1,
    defaultReps: "8",
    instructions: [
      "Start on hands and knees.",
      "Arch your back and look up (cow).",
      "Round your back and tuck your chin (cat).",
      "Move slowly between positions.",
    ],
    formCues: ["Slow transitions", "Follow your breath", "Comfortable range of motion"],
  },
  {
    slug: "shoulder-stretch",
    name: "Shoulder Stretch",
    category: "cooldown",
    difficulty: "beginner",
    equipment: "None",
    motion: "stretch",
    defaultSets: 1,
    defaultReps: "30 sec each side",
    instructions: [
      "Bring one arm across your chest.",
      "Gently hold with the opposite hand.",
      "Hold the stretch while breathing steadily.",
      "Switch sides.",
    ],
    formCues: ["Gentle hold", "Steady breathing", "Comfortable tension only"],
  },
  {
    slug: "arm-circles",
    name: "Arm Circles",
    category: "warmup",
    difficulty: "beginner",
    equipment: "None",
    motion: "twist",
    defaultSets: 1,
    defaultReps: "20 sec each direction",
    instructions: [
      "Extend your arms out to the sides.",
      "Make small circles, gradually increasing size.",
      "Reverse direction halfway through.",
    ],
    formCues: ["Controlled motion", "Relaxed shoulders", "Comfortable range"],
  },
  {
    slug: "wall-sit",
    name: "Wall Sit",
    category: "lowerBody",
    difficulty: "intermediate",
    equipment: "Wall",
    motion: "squat",
    defaultSets: 3,
    defaultReps: "30 sec",
    instructions: [
      "Lean your back against a wall.",
      "Slide down until your knees are bent around 90 degrees.",
      "Hold the position while breathing steadily.",
      "Slide back up to finish.",
    ],
    formCues: ["Steady breathing", "Comfortable hold duration", "Even weight distribution"],
  },
];

export function getExerciseBySlug(slug: string): Exercise | undefined {
  return EXERCISES.find((e) => e.slug === slug);
}
