import { Exercise } from "./types";

/**
 * The exercise library. Every entry's `motion` maps to the single shared
 * <ExerciseAnimation /> component — never a one-off animation per exercise.
 */
export const EXERCISES: Exercise[] = [
  {
    slug: "squat",
    name: "Squat",
    category: "lowerBody",
    difficulty: "beginner",
    equipment: "None",
    motion: "squat",
    defaultSets: 3,
    defaultReps: "12",
    instructions: [
      "Stand with feet approximately shoulder-width apart.",
      "Keep your chest upright.",
      "Bend your knees and hips.",
      "Lower yourself in a controlled movement.",
      "Return to the starting position.",
    ],
    formCues: ["Controlled movement", "Stable posture", "Comfortable range of motion"],
    commonMistakes: ["Letting your knees cave inward", "Rounding your lower back", "Lifting your heels off the ground"],
    youtubeUrl: "https://www.youtube.com/watch?v=VK8srrv3CvA",
  },
  {
    slug: "push-up",
    name: "Push-up",
    category: "upperBody",
    difficulty: "intermediate",
    equipment: "None",
    motion: "pushup",
    defaultSets: 3,
    defaultReps: "10",
    instructions: [
      "Place hands slightly wider than shoulder-width on the floor.",
      "Keep your body in a straight line.",
      "Lower your chest toward the floor.",
      "Push back up to the starting position.",
    ],
    formCues: ["Controlled descent", "Straight body line", "Comfortable range of motion"],
    commonMistakes: ["Letting your hips sag toward the floor", "Flaring elbows out too wide", "Only lowering halfway"],
    youtubeUrl: "https://www.youtube.com/watch?v=AHM-RGnPTug",
  },
  {
    slug: "lunge",
    name: "Lunge",
    category: "lowerBody",
    difficulty: "beginner",
    equipment: "None",
    motion: "lunge",
    defaultSets: 3,
    defaultReps: "10",
    instructions: [
      "Stand tall with feet hip-width apart.",
      "Step forward with one leg.",
      "Lower your hips until both knees are bent.",
      "Push back to the starting position.",
      "Alternate legs.",
    ],
    formCues: ["Controlled step", "Stable posture", "Comfortable depth"],
    commonMistakes: ["Letting your front knee travel past your toes", "Leaning your torso too far forward", "Taking a step that's too short"],
    youtubeUrl: "https://www.youtube.com/watch?v=tRalDvBwZqg",
  },
  {
    slug: "plank",
    name: "Plank",
    category: "core",
    difficulty: "beginner",
    equipment: "None",
    motion: "plank",
    defaultSets: 3,
    defaultReps: "30 sec",
    instructions: [
      "Rest on your forearms and toes.",
      "Keep your body in a straight line.",
      "Engage your core.",
      "Hold the position while breathing steadily.",
    ],
    formCues: ["Neutral spine", "Steady breathing", "Comfortable hold duration"],
    commonMistakes: ["Letting your hips pike up into an upside-down V", "Letting your hips sag toward the floor", "Holding your breath"],
    youtubeUrl: "https://www.youtube.com/watch?v=rzHRA7S96_E",
  },
  {
    slug: "glute-bridge",
    name: "Glute Bridge",
    category: "lowerBody",
    difficulty: "beginner",
    equipment: "None",
    motion: "bridge",
    defaultSets: 3,
    defaultReps: "15",
    instructions: [
      "Lie on your back with knees bent, feet flat.",
      "Press through your heels and lift your hips.",
      "Pause briefly at the top.",
      "Lower back down with control.",
    ],
    formCues: ["Controlled lift", "Engage glutes", "Comfortable range of motion"],
    commonMistakes: ["Barely lifting your hips off the ground", "Overarching your lower back at the top", "Pushing through your toes instead of your heels"],
    youtubeUrl: "https://www.youtube.com/watch?v=EEtd0uY-bMw",
  },
  {
    slug: "jumping-jacks",
    name: "Jumping Jacks",
    category: "cardio",
    difficulty: "beginner",
    equipment: "None",
    motion: "jump",
    defaultSets: 3,
    defaultReps: "30 sec",
    instructions: [
      "Stand with feet together, arms at your sides.",
      "Jump while spreading your legs and raising your arms.",
      "Jump back to the starting position.",
      "Repeat at a steady pace.",
    ],
    formCues: ["Steady rhythm", "Soft landings", "Comfortable pace"],
    commonMistakes: ["Not raising your arms fully overhead", "Landing stiff-legged instead of softly", "Rushing the pace until form breaks down"],
    youtubeUrl: "https://www.youtube.com/watch?v=uLVt6u15L98",
  },
  {
    slug: "mountain-climbers",
    name: "Mountain Climbers",
    category: "cardio",
    difficulty: "intermediate",
    equipment: "None",
    motion: "plank",
    defaultSets: 3,
    defaultReps: "30 sec",
    instructions: [
      "Start in a plank position.",
      "Drive one knee toward your chest.",
      "Switch legs quickly.",
      "Keep your core engaged throughout.",
    ],
    formCues: ["Steady pace", "Stable hips", "Comfortable range of motion"],
    commonMistakes: ["Letting your hips pike up as you speed up", "Bouncing your hips side to side", "Losing the straight-line plank position"],
    youtubeUrl: "https://www.youtube.com/watch?v=OR1eel_5oAY",
  },
  {
    slug: "bicycle-crunch",
    name: "Bicycle Crunch",
    category: "core",
    difficulty: "intermediate",
    equipment: "None",
    motion: "twist",
    defaultSets: 3,
    defaultReps: "15",
    instructions: [
      "Lie on your back with hands behind your head.",
      "Bring one knee toward your chest while rotating the opposite elbow toward it.",
      "Switch sides in a pedaling motion.",
      "Keep the movement controlled.",
    ],
    formCues: ["Controlled rotation", "Steady breathing", "Comfortable pace"],
    commonMistakes: ["Pulling on your neck with your hands", "Rushing through reps without rotating", "Letting your lower back arch off the floor"],
    youtubeUrl: "https://www.youtube.com/watch?v=tCSEga7I1l8",
  },
  {
    slug: "superman",
    name: "Superman",
    category: "mobility",
    difficulty: "beginner",
    equipment: "None",
    motion: "stretch",
    defaultSets: 3,
    defaultReps: "12",
    instructions: [
      "Lie face down with arms extended overhead.",
      "Lift your arms, chest, and legs off the floor together.",
      "Hold briefly at the top.",
      "Lower back down with control.",
    ],
    formCues: ["Controlled lift", "Steady breathing", "Comfortable range of motion"],
    commonMistakes: ["Yanking upward using momentum", "Holding your breath", "Lifting only your arms and not your chest"],
    youtubeUrl: "https://www.youtube.com/watch?v=hd3m4Ueiiuo",
  },
  {
    slug: "dead-bug",
    name: "Dead Bug",
    category: "core",
    difficulty: "beginner",
    equipment: "None",
    motion: "bridge",
    defaultSets: 3,
    defaultReps: "12",
    instructions: [
      "Lie on your back with arms reaching toward the ceiling and knees bent at 90 degrees.",
      "Slowly lower one arm and the opposite leg toward the floor.",
      "Return to the starting position with control.",
      "Alternate sides.",
    ],
    formCues: ["Lower back stays flat", "Controlled tempo", "Comfortable range of motion"],
    commonMistakes: ["Letting your lower back arch off the floor", "Moving too fast to stay controlled", "Letting the moving leg and arm rush ahead of each other"],
    youtubeUrl: "https://www.youtube.com/watch?v=lqnuY3wiBzA",
  },
  {
    slug: "flutter-kicks",
    name: "Flutter Kicks",
    category: "core",
    difficulty: "intermediate",
    equipment: "None",
    motion: "bridge",
    defaultSets: 3,
    defaultReps: "30 sec",
    instructions: [
      "Lie on your back with legs extended and hands under your hips.",
      "Lift both legs slightly off the floor.",
      "Alternate small up-and-down kicks.",
      "Keep your lower back pressed into the floor.",
    ],
    formCues: ["Small controlled kicks", "Lower back stays flat", "Steady breathing"],
    commonMistakes: ["Letting your lower back arch off the floor", "Kicking with legs too high to control", "Holding your breath"],
    youtubeUrl: "https://www.youtube.com/watch?v=vHxbqt9ApdM",
  },
  {
    slug: "toe-touchers",
    name: "Toe Touchers",
    category: "cooldown",
    difficulty: "beginner",
    equipment: "None",
    motion: "twist",
    defaultSets: 2,
    defaultReps: "12",
    instructions: [
      "Lie on your back with legs raised toward the ceiling.",
      "Reach both hands up toward your toes, lifting your shoulders.",
      "Lower back down with control.",
      "Repeat at a steady pace.",
    ],
    formCues: ["Controlled reach", "Steady breathing", "Comfortable range of motion"],
    commonMistakes: ["Using momentum to jerk upward", "Only lifting your arms and not your shoulders", "Rushing through reps"],
    youtubeUrl: "https://www.youtube.com/watch?v=rHEzFsLf4-o",
  },
  {
    slug: "standing-hip-circles",
    name: "Standing Hip Circles",
    category: "warmup",
    difficulty: "beginner",
    equipment: "None",
    motion: "twist",
    defaultSets: 1,
    defaultReps: "20 sec each direction",
    instructions: [
      "Stand tall with hands on your hips.",
      "Circle your hips slowly in one direction.",
      "Reverse direction halfway through.",
      "Keep your upper body relaxed.",
    ],
    formCues: ["Slow controlled circles", "Relaxed upper body", "Comfortable range"],
    commonMistakes: ["Rushing through circles before warming up", "Locking your knees", "Moving your shoulders instead of your hips"],
    youtubeUrl: "https://www.youtube.com/watch?v=JYqLwajOGjI",
  },
  {
    slug: "shoulder-stretch",
    name: "Shoulder Stretch",
    category: "cooldown",
    difficulty: "beginner",
    equipment: "None",
    motion: "stretch",
    defaultSets: 1,
    defaultReps: "30 sec each side",
    instructions: [
      "Bring one arm across your chest.",
      "Gently hold with the opposite hand.",
      "Hold the stretch while breathing steadily.",
      "Switch sides.",
    ],
    formCues: ["Gentle hold", "Steady breathing", "Comfortable tension only"],
    commonMistakes: ["Bouncing or jerking into the stretch", "Pulling hard enough to feel sharp pain", "Shrugging your shoulder up toward your ear"],
    youtubeUrl: "https://www.youtube.com/watch?v=swvXpKN832E",
  },
  {
    slug: "arm-circles",
    name: "Arm Circles",
    category: "warmup",
    difficulty: "beginner",
    equipment: "None",
    motion: "twist",
    defaultSets: 1,
    defaultReps: "20 sec each direction",
    instructions: [
      "Extend your arms out to the sides.",
      "Make small circles, gradually increasing size.",
      "Reverse direction halfway through.",
    ],
    formCues: ["Controlled motion", "Relaxed shoulders", "Comfortable range"],
    commonMistakes: ["Shrugging your shoulders up toward your ears", "Swinging too fast for control", "Starting with circles too large before warming up"],
    youtubeUrl: "https://www.youtube.com/watch?v=hne3nHGXPRM",
  },
  {
    slug: "abdominal-crunches",
    name: "Abdominal Crunches",
    category: "core",
    difficulty: "beginner",
    equipment: "None",
    motion: "twist",
    defaultSets: 3,
    defaultReps: "16",
    instructions: [
      "Lie on your back with knees bent, feet flat.",
      "Place your hands lightly behind your head.",
      "Curl your shoulders up toward your knees.",
      "Lower back down with control.",
    ],
    formCues: ["Controlled curl", "Steady breathing", "Comfortable range of motion"],
    commonMistakes: ["Pulling on your neck with your hands", "Using momentum instead of your core", "Only lifting your head, not your shoulders"],
    youtubeUrl: "https://www.youtube.com/watch?v=IqjXkf3uBQ0",
  },
  {
    slug: "russian-twist",
    name: "Russian Twist",
    category: "core",
    difficulty: "intermediate",
    equipment: "None",
    motion: "twist",
    defaultSets: 3,
    defaultReps: "20",
    instructions: [
      "Sit with knees bent, leaning back slightly.",
      "Lift your feet off the floor if comfortable.",
      "Rotate your torso to tap the floor on each side.",
      "Keep the movement controlled.",
    ],
    formCues: ["Controlled rotation", "Engaged core", "Comfortable pace"],
    commonMistakes: ["Rotating only your arms instead of your torso", "Rounding your back", "Moving too fast to stay controlled"],
    youtubeUrl: "https://www.youtube.com/watch?v=nhFynCkYtD4",
  },
  {
    slug: "heel-touch",
    name: "Heel Touch",
    category: "core",
    difficulty: "beginner",
    equipment: "None",
    motion: "twist",
    defaultSets: 3,
    defaultReps: "20",
    instructions: [
      "Lie on your back with knees bent, feet flat.",
      "Reach one hand toward the same-side heel.",
      "Return to center and switch sides.",
      "Keep the movement controlled.",
    ],
    formCues: ["Small controlled lift", "Steady breathing", "Comfortable range of motion"],
    commonMistakes: ["Lifting your whole torso instead of just crunching sideways", "Rushing through reps", "Letting your lower back arch off the floor"],
    youtubeUrl: "https://www.youtube.com/watch?v=Q-e4A0UpYdc",
  },
  {
    slug: "leg-raises",
    name: "Leg Raises",
    category: "core",
    difficulty: "intermediate",
    equipment: "None",
    motion: "bridge",
    defaultSets: 3,
    defaultReps: "16",
    instructions: [
      "Lie on your back with legs straight.",
      "Keep your lower back pressed into the floor.",
      "Raise your legs toward vertical with control.",
      "Lower back down without letting your back arch.",
    ],
    formCues: ["Controlled lift", "Lower back stays flat", "Comfortable range of motion"],
    commonMistakes: ["Letting your lower back arch off the floor", "Using momentum to swing your legs up", "Only lowering halfway with control"],
    youtubeUrl: "https://www.youtube.com/watch?v=zJukDl0Lv4U",
  },
  {
    slug: "step-up-knee-raise",
    name: "Step-up with Knee Raise",
    category: "lowerBody",
    difficulty: "intermediate",
    equipment: "Step or sturdy chair",
    motion: "squat",
    defaultSets: 3,
    defaultReps: "12 each side",
    instructions: [
      "Stand facing a step or sturdy chair.",
      "Step up, driving the opposite knee up toward your chest.",
      "Step back down with control.",
      "Alternate legs.",
    ],
    formCues: ["Controlled step", "Stable posture", "Comfortable pace"],
    commonMistakes: ["Pushing off the trailing leg instead of the stepping leg", "Letting your knee cave inward", "Rushing the pace until form breaks down"],
    youtubeUrl: "https://www.youtube.com/watch?v=wGoKb6mPJzU",
  },
  {
    slug: "pull-up",
    name: "Pull-Up",
    category: "strength",
    difficulty: "advanced",
    equipment: "Pull-up bar",
    motion: "pushup",
    defaultSets: 3,
    defaultReps: "8",
    instructions: [
      "Hang from a pull-up bar with an overhand grip, hands slightly wider than shoulders.",
      "Pull your chest up toward the bar, driving your elbows down.",
      "Pause briefly at the top.",
      "Lower back down with control until your arms are fully extended.",
    ],
    formCues: ["Full range of motion", "Controlled descent", "Engaged shoulders and core"],
    commonMistakes: ["Using momentum to swing or kip", "Only doing half reps", "Letting your shoulders shrug up toward your ears"],
    youtubeUrl: "https://www.youtube.com/watch?v=epCWPz0By50",
  },
];

export function getExerciseBySlug(slug: string): Exercise | undefined {
  return EXERCISES.find((e) => e.slug === slug);
}
