import { Exercise } from "./types";

/**
 * The exercise library. Every entry's `motion` maps to the single shared
 * <ExerciseAnimation /> component — never a one-off animation per exercise.
 */
export const EXERCISES: Exercise[] = [
  {
    slug: "squat",
    name: "Squat",
    category: "lowerBody",
    difficulty: "beginner",
    equipment: "None",
    motion: "squat",
    defaultSets: 3,
    defaultReps: "12",
    instructions: [
      "Stand with feet approximately shoulder-width apart.",
      "Keep your chest upright.",
      "Bend your knees and hips.",
      "Lower yourself in a controlled movement.",
      "Return to the starting position.",
    ],
    formCues: ["Controlled movement", "Stable posture", "Comfortable range of motion"],
    commonMistakes: ["Letting your knees cave inward", "Rounding your lower back", "Lifting your heels off the ground"],
  },
  {
    slug: "push-up",
    name: "Push-up",
    category: "upperBody",
    difficulty: "intermediate",
    equipment: "None",
    motion: "pushup",
    defaultSets: 3,
    defaultReps: "10",
    instructions: [
      "Place hands slightly wider than shoulder-width on the floor.",
      "Keep your body in a straight line.",
      "Lower your chest toward the floor.",
      "Push back up to the starting position.",
    ],
    formCues: ["Controlled descent", "Straight body line", "Comfortable range of motion"],
    commonMistakes: ["Letting your hips sag toward the floor", "Flaring elbows out too wide", "Only lowering halfway"],
  },
  {
    slug: "lunge",
    name: "Lunge",
    category: "lowerBody",
    difficulty: "beginner",
    equipment: "None",
    motion: "lunge",
    defaultSets: 3,
    defaultReps: "10",
    instructions: [
      "Stand tall with feet hip-width apart.",
      "Step forward with one leg.",
      "Lower your hips until both knees are bent.",
      "Push back to the starting position.",
      "Alternate legs.",
    ],
    formCues: ["Controlled step", "Stable posture", "Comfortable depth"],
    commonMistakes: ["Letting your front knee travel past your toes", "Leaning your torso too far forward", "Taking a step that's too short"],
  },
  {
    slug: "plank",
    name: "Plank",
    category: "core",
    difficulty: "beginner",
    equipment: "None",
    motion: "plank",
    defaultSets: 3,
    defaultReps: "30 sec",
    instructions: [
      "Rest on your forearms and toes.",
      "Keep your body in a straight line.",
      "Engage your core.",
      "Hold the position while breathing steadily.",
    ],
    formCues: ["Neutral spine", "Steady breathing", "Comfortable hold duration"],
    commonMistakes: ["Letting your hips pike up into an upside-down V", "Letting your hips sag toward the floor", "Holding your breath"],
  },
  {
    slug: "glute-bridge",
    name: "Glute Bridge",
    category: "lowerBody",
    difficulty: "beginner",
    equipment: "None",
    motion: "bridge",
    defaultSets: 3,
    defaultReps: "15",
    instructions: [
      "Lie on your back with knees bent, feet flat.",
      "Press through your heels and lift your hips.",
      "Pause briefly at the top.",
      "Lower back down with control.",
    ],
    formCues: ["Controlled lift", "Engage glutes", "Comfortable range of motion"],
    commonMistakes: ["Barely lifting your hips off the ground", "Overarching your lower back at the top", "Pushing through your toes instead of your heels"],
  },
  {
    slug: "jumping-jacks",
    name: "Jumping Jacks",
    category: "cardio",
    difficulty: "beginner",
    equipment: "None",
    motion: "jump",
    defaultSets: 3,
    defaultReps: "30 sec",
    instructions: [
      "Stand with feet together, arms at your sides.",
      "Jump while spreading your legs and raising your arms.",
      "Jump back to the starting position.",
      "Repeat at a steady pace.",
    ],
    formCues: ["Steady rhythm", "Soft landings", "Comfortable pace"],
    commonMistakes: ["Not raising your arms fully overhead", "Landing stiff-legged instead of softly", "Rushing the pace until form breaks down"],
  },
  {
    slug: "mountain-climbers",
    name: "Mountain Climbers",
    category: "cardio",
    difficulty: "intermediate",
    equipment: "None",
    motion: "plank",
    defaultSets: 3,
    defaultReps: "30 sec",
    instructions: [
      "Start in a plank position.",
      "Drive one knee toward your chest.",
      "Switch legs quickly.",
      "Keep your core engaged throughout.",
    ],
    formCues: ["Steady pace", "Stable hips", "Comfortable range of motion"],
    commonMistakes: ["Letting your hips pike up as you speed up", "Bouncing your hips side to side", "Losing the straight-line plank position"],
  },
  {
    slug: "bicycle-crunch",
    name: "Bicycle Crunch",
    category: "core",
    difficulty: "intermediate",
    equipment: "None",
    motion: "twist",
    defaultSets: 3,
    defaultReps: "15",
    instructions: [
      "Lie on your back with hands behind your head.",
      "Bring one knee toward your chest while rotating the opposite elbow toward it.",
      "Switch sides in a pedaling motion.",
      "Keep the movement controlled.",
    ],
    formCues: ["Controlled rotation", "Steady breathing", "Comfortable pace"],
    commonMistakes: ["Pulling on your neck with your hands", "Rushing through reps without rotating", "Letting your lower back arch off the floor"],
  },
  {
    slug: "cat-cow",
    name: "Cat-Cow Stretch",
    category: "mobility",
    difficulty: "beginner",
    equipment: "None",
    motion: "stretch",
    defaultSets: 1,
    defaultReps: "8",
    instructions: [
      "Start on hands and knees.",
      "Arch your back and look up (cow).",
      "Round your back and tuck your chin (cat).",
      "Move slowly between positions.",
    ],
    formCues: ["Slow transitions", "Follow your breath", "Comfortable range of motion"],
    commonMistakes: ["Bouncing quickly between positions", "Holding your breath instead of moving with it", "Forcing a bigger arch than feels comfortable"],
  },
  {
    slug: "shoulder-stretch",
    name: "Shoulder Stretch",
    category: "cooldown",
    difficulty: "beginner",
    equipment: "None",
    motion: "stretch",
    defaultSets: 1,
    defaultReps: "30 sec each side",
    instructions: [
      "Bring one arm across your chest.",
      "Gently hold with the opposite hand.",
      "Hold the stretch while breathing steadily.",
      "Switch sides.",
    ],
    formCues: ["Gentle hold", "Steady breathing", "Comfortable tension only"],
    commonMistakes: ["Bouncing or jerking into the stretch", "Pulling hard enough to feel sharp pain", "Shrugging your shoulder up toward your ear"],
  },
  {
    slug: "arm-circles",
    name: "Arm Circles",
    category: "warmup",
    difficulty: "beginner",
    equipment: "None",
    motion: "twist",
    defaultSets: 1,
    defaultReps: "20 sec each direction",
    instructions: [
      "Extend your arms out to the sides.",
      "Make small circles, gradually increasing size.",
      "Reverse direction halfway through.",
    ],
    formCues: ["Controlled motion", "Relaxed shoulders", "Comfortable range"],
    commonMistakes: ["Shrugging your shoulders up toward your ears", "Swinging too fast for control", "Starting with circles too large before warming up"],
  },
  {
    slug: "abdominal-crunches",
    name: "Abdominal Crunches",
    category: "core",
    difficulty: "beginner",
    equipment: "None",
    motion: "twist",
    defaultSets: 3,
    defaultReps: "16",
    instructions: [
      "Lie on your back with knees bent, feet flat.",
      "Place your hands lightly behind your head.",
      "Curl your shoulders up toward your knees.",
      "Lower back down with control.",
    ],
    formCues: ["Controlled curl", "Steady breathing", "Comfortable range of motion"],
    commonMistakes: ["Pulling on your neck with your hands", "Using momentum instead of your core", "Only lifting your head, not your shoulders"],
  },
  {
    slug: "russian-twist",
    name: "Russian Twist",
    category: "core",
    difficulty: "intermediate",
    equipment: "None",
    motion: "twist",
    defaultSets: 3,
    defaultReps: "20",
    instructions: [
      "Sit with knees bent, leaning back slightly.",
      "Lift your feet off the floor if comfortable.",
      "Rotate your torso to tap the floor on each side.",
      "Keep the movement controlled.",
    ],
    formCues: ["Controlled rotation", "Engaged core", "Comfortable pace"],
    commonMistakes: ["Rotating only your arms instead of your torso", "Rounding your back", "Moving too fast to stay controlled"],
  },
  {
    slug: "heel-touch",
    name: "Heel Touch",
    category: "core",
    difficulty: "beginner",
    equipment: "None",
    motion: "twist",
    defaultSets: 3,
    defaultReps: "20",
    instructions: [
      "Lie on your back with knees bent, feet flat.",
      "Reach one hand toward the same-side heel.",
      "Return to center and switch sides.",
      "Keep the movement controlled.",
    ],
    formCues: ["Small controlled lift", "Steady breathing", "Comfortable range of motion"],
    commonMistakes: ["Lifting your whole torso instead of just crunching sideways", "Rushing through reps", "Letting your lower back arch off the floor"],
  },
  {
    slug: "leg-raises",
    name: "Leg Raises",
    category: "core",
    difficulty: "intermediate",
    equipment: "None",
    motion: "bridge",
    defaultSets: 3,
    defaultReps: "16",
    instructions: [
      "Lie on your back with legs straight.",
      "Keep your lower back pressed into the floor.",
      "Raise your legs toward vertical with control.",
      "Lower back down without letting your back arch.",
    ],
    formCues: ["Controlled lift", "Lower back stays flat", "Comfortable range of motion"],
    commonMistakes: ["Letting your lower back arch off the floor", "Using momentum to swing your legs up", "Only lowering halfway with control"],
  },
  {
    slug: "wall-sit",
    name: "Wall Sit",
    category: "lowerBody",
    difficulty: "intermediate",
    equipment: "Wall",
    motion: "squat",
    defaultSets: 3,
    defaultReps: "30 sec",
    instructions: [
      "Lean your back against a wall.",
      "Slide down until your knees are bent around 90 degrees.",
      "Hold the position while breathing steadily.",
      "Slide back up to finish.",
    ],
    formCues: ["Steady breathing", "Comfortable hold duration", "Even weight distribution"],
    commonMistakes: ["Letting your knees cave inward", "Sliding your feet too close to the wall", "Holding your breath during the hold"],
  },
];

export function getExerciseBySlug(slug: string): Exercise | undefined {
  return EXERCISES.find((e) => e.slug === slug);
}
